# Create a Tournament
POST http://{{host}}:{{port}}/tournaments/{{$uuid}}
content-type: application-json

###
# Delete a Tournament
DELETE http://{{host}}:{{port}}/tournaments/8ffdabc9-12eb-4a76-b719-4338d71e4555
content-type: application-json

###
# Get Tournaments
GET http://{{host}}:{{port}}/tournaments/?active=true
content-type: application-json
